apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432  # Internal Cluster IP Port
      targetPort: 5432
  clusterIP: 10.108.24.100  # Headless service for internal access

